window.CHEESE_BINGO_CONFIG = {
  id: 'fall-romantiverse-2026',
  movie: 'Fall Romantiverse Bingo',
  network: 'Cheese Louise',
  season: 'Fall',
  holiday: 'Autumn',
  subtitle: 'Fall in the Romantiverse',
  description: 'A general fall bingo card for cheesy romance movies: pumpkins, festivals, flannel, cider, leaves, hometowns, cozy drinks, and aggressively photogenic autumn nonsense.',
  freeSpace: 'CHEESE LOUISE!',

  // Broad fall staples that appear on every randomized card.
  required: [
    'pumpkins',
    'fall-festival',
    'cozy-drink',
    'plaid-flannel',
    'scenic-leaves'
  ],

  // Common fall-romance beats are slightly more likely to appear.
  weighted: [
    'small-town',
    'hometown-return',
    'hayride',
    'apple-cider',
    'pumpkin-patch',
    'fall-decor',
    'family-business',
    'old-flame',
    'rivals-to-lovers',
    'town-event',
    'cozy-sweater'
  ],

  // New Card should materially change the board, not merely rearrange it.
  minTraitChanges: 8,

  pool: [
    { id:'pumpkins', label:'Pumpkins everywhere' },
    { id:'pumpkin-patch', label:'Pumpkin patch' },
    { id:'pumpkin-carving', label:'Pumpkin carving' },
    { id:'pumpkin-food', label:'Pumpkin-flavored something' },
    { id:'fall-festival', label:'Fall festival' },
    { id:'town-event', label:'Whole town at one event' },
    { id:'hayride', label:'Hayride' },
    { id:'corn-maze', label:'Corn maze' },
    { id:'apple-picking', label:'Apple picking' },
    { id:'candy-apples', label:'Candy apples' },
    { id:'apple-cider', label:'Apple cider' },
    { id:'cozy-drink', label:'Cozy seasonal drink' },
    { id:'coffee-shop', label:'Small-town coffee shop' },
    { id:'bakery', label:'Bakery full of fall treats' },
    { id:'plaid-flannel', label:'Plaid or flannel' },
    { id:'cozy-sweater', label:'Cozy sweater' },
    { id:'scarf-weather', label:'Decorative scarf weather' },
    { id:'boots', label:'Fall boots' },
    { id:'scenic-leaves', label:'Gorgeous leaf shot' },
    { id:'leaf-pile', label:'Leaves used as scenery' },
    { id:'fall-decor', label:'Autumn décor overload' },
    { id:'wreath', label:'Fall wreath' },
    { id:'string-lights', label:'String lights at an outdoor event' },
    { id:'small-town', label:'Perfect little small town' },
    { id:'hometown-return', label:'Returns to hometown' },
    { id:'big-city-job', label:'Big-city job mentioned' },
    { id:'city-vs-home', label:'City life vs. hometown life' },
    { id:'family-business', label:'Family business' },
    { id:'save-business', label:'Family business needs saving' },
    { id:'family-farm', label:'Family farm or orchard' },
    { id:'inn-bnb', label:'Inn, lodge, or B&B' },
    { id:'main-street', label:'Quaint Main Street' },
    { id:'old-flame', label:'Old flame reappears' },
    { id:'childhood-sweetheart', label:'Childhood sweetheart' },
    { id:'rivals-to-lovers', label:'Rivals-to-lovers chemistry' },
    { id:'friends-to-lovers', label:'Friends-to-lovers energy' },
    { id:'competitive-flirting', label:'Competitive flirting' },
    { id:'forced-together', label:'Forced to work together' },
    { id:'town-matchmaking', label:'Town is clearly matchmaking' },
    { id:'family-matchmaking', label:'Family is clearly matchmaking' },
    { id:'shared-blanket', label:'Conveniently shared blanket' },
    { id:'almost-kiss', label:'Almost kiss' },
    { id:'interrupted-kiss', label:'Interrupted kiss' },
    { id:'misunderstanding', label:'One-sentence misunderstanding' },
    { id:'career-or-love', label:'Career-or-love decision' },
    { id:'grand-gesture', label:'Grand romantic gesture' },
    { id:'community-saves-day', label:'Community saves the day' },
    { id:'family-legacy', label:'Family legacy speech' },
    { id:'town-knows', label:'Whole town knows before they do' },
    { id:'wholesome-work', label:'Wholesome work montage' },
    { id:'empty-coffee-cup', label:'Coffee cup is clearly empty' },
    { id:'perfect-weather', label:'Impossibly perfect fall weather' },
    { id:'outdoor-date', label:'Outdoor fall date' },
    { id:'bonfire-firepit', label:'Bonfire or fire pit' },
    { id:'barn', label:'Barn or rustic setting' },
    { id:'dog', label:'Adorable dog gets screen time' },
    { id:'farmers-market', label:'Farmers market or craft booths' },
    { id:'pie-contest', label:'Pie, baking, or food contest' },
    { id:'friendly-competition', label:'Friendly competition' },
    { id:'festival-crisis', label:'Festival suddenly has a crisis' }
  ]
};
