window.CHEESE_BINGO_CONFIG = {
  id: 'love-fall-and-order-2019',
  movie: 'Love, Fall & Order',
  network: 'Hallmark Channel',
  season: 'Fall',
  holiday: 'Non-Holiday',
  subtitle: 'This week in the Romantiverse',
  description: 'Manhattan property lawyer Claire Hart returns home to help save her dad\'s annual Fall Fest on the family pumpkin farm, only to face her old high-school rival Patrick as opposing counsel in a property-line dispute.',
  freeSpace: 'CHEESE LOUISE!',

  // Movie-defining traits that appear on every randomized card.
  required: [
    'family-pumpkin-farm',
    'fall-fest',
    'property-line-dispute',
    'opposing-lawyer-old-rival',
    'rivals-to-lovers'
  ],

  // Highly characteristic moments are more likely to appear, but not guaranteed.
  weighted: [
    'manhattan-lawyer',
    'small-town-return',
    'pumpkins-everywhere',
    'trivia-competition',
    'pumpkin-muffin',
    'candy-apples',
    'romantic-hayride',
    'empty-coffee-cup',
    'leaf-peepers',
    'city-boyfriend-complication',
    'community-saves-festival'
  ],

  // New Card should materially change the board, not merely rearrange it.
  minTraitChanges: 8,

  pool: [
    { id:'manhattan-lawyer', label:'Manhattan corporate lawyer' },
    { id:'property-law-specialist', label:'Property law becomes the plot' },
    { id:'small-town-return', label:'Big-city heroine returns home' },
    { id:'dad-calls-her-home', label:'Dad needs his daughter back home' },
    { id:'family-pumpkin-farm', label:'Family pumpkin farm' },
    { id:'fall-fest', label:'Fall Fest is serious business' },
    { id:'festival-in-danger', label:'The beloved festival is in danger' },
    { id:'property-line-dispute', label:'Property-line dispute' },
    { id:'old-deed', label:'Old deed / document changes everything' },
    { id:'legal-files-come-out', label:'Maps, deeds or legal files come out' },
    { id:'opposing-lawyer-old-rival', label:'Opposing lawyer is an old rival' },
    { id:'high-school-rivalry', label:'High-school rivalry gets mentioned' },
    { id:'rivals-to-lovers', label:'Rivals-to-lovers chemistry' },
    { id:'lawyer-v-lawyer', label:'Lawyer vs. lawyer showdown' },
    { id:'legal-talk-turns-personal', label:'Legal talk turns personal' },
    { id:'competitive-flirting', label:'Competitive flirting' },
    { id:'trivia-competition', label:'Trivia competition' },
    { id:'free-chili-prize', label:'Free chili becomes a prize' },
    { id:'pumpkin-muffin', label:'Pumpkin muffin appears' },
    { id:'candy-apples', label:'Candy apples' },
    { id:'romantic-hayride', label:'Romantic hayride' },
    { id:'shared-blanket', label:'Conveniently shared blanket' },
    { id:'kettle-corn', label:'Kettle corn at the festival' },
    { id:'leaf-peepers', label:'Leaf peepers appear' },
    { id:'empty-coffee-cup', label:'Coffee cup is clearly empty' },
    { id:'dog-maple', label:'Maple the dog steals the scene' },
    { id:'flower-shop', label:'Small-town flower shop' },
    { id:'land-for-flowers', label:'The disputed land is needed for flowers' },
    { id:'family-legacy', label:'Family legacy speech' },
    { id:'city-boyfriend-complication', label:'City boyfriend complication' },
    { id:'boyfriend-misunderstanding', label:'Boyfriend misunderstanding' },
    { id:'friends-see-it-coming', label:'Friends see the romance coming' },
    { id:'town-needs-festival', label:'The town needs the Fall Fest' },
    { id:'old-land-grudge', label:'Old family land disagreement resurfaces' },
    { id:'courthouse-scene', label:'Courthouse scene' },
    { id:'horse-carriage-gag', label:'Horse-drawn carriage small-town gag' },
    { id:'pumpkins-everywhere', label:'Pumpkins absolutely everywhere' },
    { id:'courthouse-pumpkins', label:'Even the courthouse gets pumpkins' },
    { id:'fall-decor-overload', label:'Autumn décor overload' },
    { id:'fake-fall-leaves', label:'Suspiciously perfect fall leaves' },
    { id:'vermont-small-town', label:'Peak Vermont small-town fantasy' },
    { id:'city-v-hometown', label:'City life vs. hometown life' },
    { id:'career-v-home', label:'Career competes with coming home' },
    { id:'old-classmates-reconnect', label:'Old classmates reconnect' },
    { id:'professional-boundaries-blur', label:'Professional boundaries get blurry' },
    { id:'neighbor-feud', label:'Neighbor dispute becomes everybody\'s problem' },
    { id:'community-saves-festival', label:'Community solution saves the festival' },
    { id:'neighbors-work-together', label:'The feuding sides finally work together' },
    { id:'shared-festival-solution', label:'Sharing the festival solves the dispute' },
    { id:'small-town-knows-all', label:'The whole town seems to know everything' },
    { id:'plaid-flannel', label:'Peak fall plaid / flannel' },
    { id:'scenic-leaf-shot', label:'Obligatory gorgeous leaf shot' }
  ]
};
